; memories
.import __RAM_BASE_START__
.import __RAM_BASE_SIZE__
.import __RAM_BASE_LAST__

.import __RAM_BIOS_START__
.import __RAM_BIOS_SIZE__
.import __RAM_BIOS_LAST__

.import __RAM_USER_START__
.import __RAM_USER_SIZE__
.import __RAM_USER_LAST__

.import __ROM_START__
.import __ROM_SIZE__
.import __ROM_LAST__

.import __IO_START__
.import __IO_SIZE__
.import __IO_LAST__

; segments
.import __CODE_SIZE__
.import __CODE_LOAD__
.import __CODE_RUN__

.import __RODATA_RUN__
.import __RODATA_SIZE__

.import __VECTORS_RUN__
.import __VECTORS_SIZE__

.import __ZEROPAGE_RUN__
.import __ZEROPAGE_SIZE__

.import __STACK_RUN__
.import __STACK_SIZE__

.import __DATA_RUN__
.import __DATA_SIZE__

.import __BSS_RUN__
.import __BSS_SIZE__
